# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"histogram_equalize": "cld edges version-mst.ipynb",
         "raster_edges": "cld edges version-mst.ipynb",
         "extract_centerlines": "cld edges version-mst.ipynb",
         "explode_multilines": "cld edges version-mst.ipynb",
         "merge_naive": "cld edges version-mst.ipynb",
         "greedy_reorder": "cld edges version-mst.ipynb",
         "reorder_center_dist": "cld edges version-mst.ipynb",
         "reorder_start_dist": "cld edges version-mst.ipynb",
         "reorder_end_dist": "cld edges version-mst.ipynb",
         "sobel": "cld edges version-mst.ipynb",
         "sample_grad": "cld edges version-mst.ipynb",
         "triangulate": "cld edges version-mst.ipynb",
         "to_graph": "cld edges version-mst.ipynb",
         "extract_path_rec": "cld edges version-mst.ipynb",
         "extract_path": "cld edges version-mst.ipynb",
         "a_star": "cld edges version-mst.ipynb",
         "pt_vert_distance": "cld edges version-mst.ipynb",
         "nearest_line": "cld edges version-mst.ipynb",
         "mk_heuristic_fn": "cld edges version-mst.ipynb",
         "mk_weight_fn": "cld edges version-mst.ipynb",
         "tuple_sq_dist": "cld edges version-mst.ipynb",
         "insert_a_star_connections": "cld edges version-mst.ipynb",
         "pipeline": "cld edges version-mst.ipynb",
         "rgb2line": "cld edges version-mst.ipynb"}

modules = ["cld_mst.py"]

doc_url = "https://aman.github.io/blind_contour/"

git_url = "https://github.com/aman/blind_contour/tree/master/"

def custom_doc_links(name): return None
