# AUTOGENERATED! DO NOT EDIT! File to edit: grad graph.ipynb (unless otherwise specified).

__all__ = ['sobel_1d', 'sobel']

# Cell

import json
import glob
import subprocess

import cv2
import numpy as np
from matplotlib import pyplot as plt
from shapely import geometry as geom

from math import floor

# Cell

def sobel_1d(gray, vertical, scale=1, delta=1.0, order=1):
    dx, dy = (0, order) if vertical else (order, 0)
    return cv2.Sobel(gray, cv2.CV_32FC1, dx, dy, ksize=3, scale=scale, delta=delta, borderType=cv2.BORDER_DEFAULT)

def sobel(gray):
    abs_grad_x = cv2.convertScaleAbs(sobel_1d(gray, False))
    abs_grad_y = cv2.convertScaleAbs(sobel_1d(gray, True))
    grad = cv2.addWeighted(abs_grad_x, 0.5, abs_grad_y, 0.5, 0)
    return grad